system_prompt = """
system prompt of your choice
"""
user_prompt = "Write me a Cloudflare Worker using Hono."

[[models]]
model_name = "claude-3.5-sonnet"
api_key = "$KEY_HERE"
# additional_system_prompt = "Be concise."

[[models]]
model_name = "gpt-4o-mini"
api_key = "$KEY_HERE"
