[project]
name = "shootout-py"
version = "0.1.1"
description = "Run prompts against multiple Large Language Models (LLMs) and capture structured output."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["llm", "llm-cloudflare", "llm-anthropic", "tomli"]
